In [1]:
#Import Data
import pandas as pd


In [2]:
##Ecom_Cust_Survey = pd.read_csv('...',header = 0)
df = pd.read_csv('Ecom_Cust_Survey.csv',header = 0)

df.dropna(inplace=True) # to remove all the missing values rows..
#Q 1. How many customers have participated in the survey?
df.info()
#ANS: 11805


<class 'pandas.core.frame.DataFrame'>
Index: 11805 entries, 0 to 11804
Data columns (total 7 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Cust_num              11805 non-null  float64
 1   Region                11805 non-null  object 
 2   Age                   11805 non-null  float64
 3   Order Quantity        11805 non-null  float64
 4   Customer_Type         11805 non-null  object 
 5   Improvement Area      11805 non-null  object 
 6   Overall_Satisfaction  11805 non-null  object 
dtypes: float64(3), object(4)
memory usage: 737.8+ KB


In [3]:
#Q.2 Overall most of the customers are satisfied or dis-satisfied?
#total number of customers
df.shape

(11805, 7)

In [4]:
#number of satisfied customers
freq=df['Overall_Satisfaction'].value_counts(sort=False)
print(freq)


Overall_Satisfaction
Dis Satisfied    6408
Satisfied        5397
Name: count, dtype: int64


In [5]:
#Q 3. Can you segment the data and find the concentrated satisfied and dis-satisfied customer segments ?
#solution:
# We will create a tree model in python using the sci-kit module
# before that we will need to convert most of the feature data into numerical or hash values as scikit only works with numerical data


df['Region'] = df['Region'].map( {'EAST': 1, 'WEST': 2, 'NORTH': 3, 'SOUTH':4} ).astype(int)
df['Customer_Type'] = df['Customer_Type'].map({'Prime': 1, 'Non_Prime': 0}).astype(int)


In [6]:
#We will also need to change the column names, as '.' and spaces are part of many basic function in python
df.rename(columns={'Order Quantity':'Order_Quantity', 'Improvement Area' :'Improvement_Area'}, inplace=True)
df['Improvement_Area'] = df['Improvement_Area'].map({'Website UI':1, 'Packing & Shipping':2, 'Product Quality':3,}).astype(int)
df['Overall_Satisfaction'] = df['Overall_Satisfaction'].map( {'Dis Satisfied': 0, 'Satisfied': 1} ).astype(int)


In [7]:
#Need the library to create the tree
from sklearn import tree

In [8]:
#Defining Features and lables, ignoring cust_num and target variable
features= list(df.columns[2:6])


In [9]:

X = df[features]
y = df['Overall_Satisfaction']


In [10]:
#Building Tree Model
clf = tree.DecisionTreeClassifier(max_depth=2)
clf.fit(X,y)


DecisionTreeClassifier(max_depth=2)

In [11]:
#What are the major characteristics of satisfied customers?

#Plotting the trees
#Unfortunately drawing a beautiful tree is not easy in python, Still
#you will need to install pydot
#use this command in your anaconda prompt: conda install -c anaconda pydot=1.0.28


In [12]:
from IPython.display import Image
from six import StringIO

In [13]:
#LAB : Tree Validation
########################################
##########Tree Validation
#Tree Validation
X
predict1 = clf.predict(X)
predict1

array([0, 1, 1, ..., 0, 0, 1])

In [14]:
from sklearn.metrics import confusion_matrix ###for using confusion matrix###
cm = confusion_matrix(y, predict1)
print (cm)


[[6370   38]
 [ 648 4749]]


In [15]:
total = sum(sum(cm))
#####from confusion matrix calculate accuracy
accuracy = (cm[0,0]+cm[1,1])/total
print(accuracy)

0.9418890300720034


#LAB: Overfitting
#LAB: The problem of overfitting
############################################################################ 
##The problem of overfitting
#Choosing Cp and Pruning


In [16]:
#Dataset: "Buyers Profiles/Train_data.csv"
#Task 1: Import both test and training data
import pandas as pd
#Dataset: "Buyers Profiles/Train_data.csv"
#Import both test and training data
train = pd.read_csv("Train_data.csv", header=0)
test = pd.read_csv("Test_data.csv", header=0)

In [17]:
##print train.info()
train.shape
test.shape

(6, 3)

In [18]:
# Building the tree model.
# the data have string values we need to convert them into numerica values
train['Gender'] = train['Gender'].map( {'Male': 1, 'Female': 0} ).astype(int)
train['Bought'] = train['Bought'].map({'Yes':1, 'No':0}).astype(int)

In [19]:
test['Gender'] = test['Gender'].map( {'Male': 1, 'Female': 0} ).astype(int)
test['Bought'] = test['Bought'].map({'Yes':1, 'No':0}).astype(int)


In [20]:
##print train.info()
##print test.info()


In [21]:
from sklearn import tree

#Defining Features and lables
features = list(train.columns[:2])

In [22]:
X_train = train[features]
y_train = train['Bought']

In [23]:
#X_train

X_test = test[features]
y_test = test['Bought']

In [24]:
#training Tree Model
clf = tree.DecisionTreeClassifier()
clf.fit(X_train,y_train)

DecisionTreeClassifier()

In [25]:
predict1 = clf.predict(X_train)
print(predict1)

[1 1 1 0 0 1 1 1 0 0 0 1 0 0]


In [26]:
predict2 = clf.predict(X_test)
print(predict2)

[0 0 0 1 1 1]


In [27]:

####Calculation of Accuracy and Confusion Matrix
#on the train data
from sklearn.metrics import confusion_matrix ###for using confusion matrix###
cm1 = confusion_matrix(y_train,predict1)
cm1

array([[7, 0],
       [0, 7]], dtype=int64)

In [28]:
total1 = sum(sum(cm1))
#####from confusion matrix calculate accuracy
accuracy1 = (cm1[0,0]+cm1[1,1])/total1
accuracy1

1.0

In [29]:
#On Test Data
cm2 = confusion_matrix(y_test,predict2)
cm2
total2 = sum(sum(cm2))
#####from confusion matrix calculate accuracy
accuracy2 = (cm2[0,0]+cm2[1,1])/total2
accuracy2


0.16666666666666666

Pruning

In [30]:
### hyper parameters : Before creating the model ,we pass some values 
### model parameters : after creating the model

In [31]:
#We will rebuild a new tree by using above data and see how it works by tweeking the parameteres we have..
dtree = tree.DecisionTreeClassifier(max_leaf_nodes = 10, 
                                    min_samples_leaf = 5, 
                                    max_depth= 5)

In [32]:
dtree.fit(X_train,y_train)

predict3 = dtree.predict(X_train)
predict4 = dtree.predict(X_test)

In [33]:
#Accuracy of the model that we created with modified model parameters.
#on the train data
from sklearn.metrics import confusion_matrix ###for using confusion matrix###
cm1 = confusion_matrix(y_train,predict3)
cm1
total1 = sum(sum(cm1))

In [34]:
#####from confusion matrix calculate accuracy
accuracy1 = (cm1[0,0]+cm1[1,1])/total1
accuracy1

0.8571428571428571

In [35]:
#On Test Data
cm2 = confusion_matrix(y_test,predict4)
cm2
total2 = sum(sum(cm2))
#####from confusion matrix calculate accuracy
accuracy2 = (cm2[0,0]+cm2[1,1])/total2
accuracy2

0.8333333333333334

In [36]:
#lab

In [37]:
#LAB: Tree Building & Model Selection
#We will try to build a few trees tweeking the parameteres of the tree and see which works best
#Dataset: Fiber bits

In [38]:
import pandas as pd
import numpy as np

Fiber_df = pd.read_csv("Fiberbits.csv", header=0)

Fiber_df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 9 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   active_cust                 100000 non-null  int64
 1   income                      100000 non-null  int64
 2   months_on_network           100000 non-null  int64
 3   Num_complaints              100000 non-null  int64
 4   number_plan_changes         100000 non-null  int64
 5   relocated                   100000 non-null  int64
 6   monthly_bill                100000 non-null  int64
 7   technical_issues_per_month  100000 non-null  int64
 8   Speed_test_result           100000 non-null  int64
dtypes: int64(9)
memory usage: 6.9 MB


In [39]:
#good thing the data have all the values as numerical
#Modeling a decision tree
from sklearn import model_selection, tree


In [40]:
Fiber_df = pd.read_csv("Fiberbits.csv", header=0)

Fiber_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 9 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   active_cust                 100000 non-null  int64
 1   income                      100000 non-null  int64
 2   months_on_network           100000 non-null  int64
 3   Num_complaints              100000 non-null  int64
 4   number_plan_changes         100000 non-null  int64
 5   relocated                   100000 non-null  int64
 6   monthly_bill                100000 non-null  int64
 7   technical_issues_per_month  100000 non-null  int64
 8   Speed_test_result           100000 non-null  int64
dtypes: int64(9)
memory usage: 6.9 MB


In [41]:
#Defining Features and lables
features = list(Fiber_df.drop(['active_cust'],axis=1)) #this code gives a list of column names except 'active_cust'


In [42]:
X = np.array(Fiber_df[features])
y = np.array(Fiber_df['active_cust'])

In [43]:

X_train, X_test, y_train, y_test = model_selection.train_test_split(X,y, train_size = 0.8)


In [44]:
#Tree building and validation

clf1 = tree.DecisionTreeClassifier()
clf1.fit(X_train,y_train)



DecisionTreeClassifier()

In [45]:
#If we want to see the predictive values we can do this by:
#predict1 = clf1.predict(y_train)
clf1.score(X_train,y_train)

0.9972

In [46]:
clf1.score(X_test,y_test)
#This model with default parameters is giving us accuracy of 99% on training and 84.505..% 
#It is overfitted model with defalut parameters


0.8447

In [47]:
#Let's make a model by chnaging the parameters.
clf2 = tree.DecisionTreeClassifier(criterion='gini', 
                                   splitter='best', 
                                   max_depth=20, 
                                   min_samples_split=5, 
                                   min_samples_leaf=5, 
                                   max_leaf_nodes=10)
clf2.fit(X_train,y_train)

DecisionTreeClassifier(max_depth=20, max_leaf_nodes=10, min_samples_leaf=5,
                       min_samples_split=5)

In [48]:
clf.best_params_



AttributeError: 'DecisionTreeClassifier' object has no attribute 'best_params_'

In [ ]:
#Finding optimal criteria and max_depth
# optimal hyper parameters
from sklearn.model_selection import GridSearchCV
tuned_parameters = [{'criterion': ['gini','entropy'],'max_depth': range(2,10)}]
clf_tree = tree.DecisionTreeClassifier()
clf = GridSearchCV(clf1, tuned_parameters, cv=10, scoring='roc_auc')
clf.fit(X_train, y_train )


In [ ]:
clf.best_score_

In [ ]:
clf.best_params_